### ISSUE TITLE
I recommend adding to repo.

### ISSUE THREAD

**Issue by born2net** [jmcunningham/AngularJS2-Learning#5]
Thanks for a great repo... I just posted a massive Angular 2 bootstrap project. Anyone interested om Angular 2 will love it. Check out the working demo @ http://ng2.javascriptninja.io and source at: https://github.com/born2net/ng2Boilerplate

I recommend adding to repo.

regards

Sean.

**Comment by jmcunningham** [comment]
Thanks...I finally got around to rebooting this repo and added your seed project last night.
